apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ocloud-app-ingress
  namespace: ocloud-apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: ocloud.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ocloud-app-service
            port:
              number: 80
