apiVersion: v1
kind: Service
metadata:
  name: cnf-simulator-service
  labels:
    app: cnf-simulator
spec:
  # Service Type NodePort for external access
  type: NodePort
  ports:
  - port: 8080           # Port internal service
    targetPort: 8080     # Port container
    nodePort: 30080      # Port eksternal that can be accessed from outside the cluster
    protocol: TCP
    name: http
  selector:
    app: cnf-simulator   # Selector for pods managed by the deployment