apiVersion: v2
name: ocloud-app
description: A Helm chart for deploying the O-Cloud application to Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: 0.1.0
    repository: https://charts.bitnami.com/bitnami